
# NOTE can not do gitflow branch names with hyphens in the branch names

# WEIRD -SOMETIMES - TWO TAGS IN THE SAME BRANCH
version: 1.0.{build}.{branch}
# MAYBE DEV BRANCHES WOULD BE 1.1
#

#
# KEEP HERE
#

# Do not build on tags (GitHub and BitBucket)
# NOT AN ENVIRONMENT VARIABLE (BUT DOES SKIP TAGS)
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
# skip_non_tags: true

# ( ) IS A LOGICAL 'AND'
# (-) IS A LOGICAL 'OR'

# IMPLIED - ROOT MATRIX

# WILL DO BOTH COMBINATIONS
platform:
  - 'x64'
  - 'x86'

# WILL DO BOTH COMBINATIONS
configuration:
  - 'Debug'
  - 'Release'

# WORKS (RESTRICTS ROOT LEVEL)
matrix:
  exclude:
    # ( ) IS A LOGICAL 'AND'
    # (-) IS A LOGICAL 'OR'
    - platform: 'x86'
      configuration: 'Debug'

init:
 - sh: if [ "${CONFIGURATION}" = "Debug" ] && ; then exit 0; else  ;fi
 - sh: if [ "${PLATFORM}" = "x86" ]; then exit 0; fi

environment:
  #
  # these variables are common to all jobs
  #
  AUTHOR: Andre Mikulec
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  #
  # THE ONE AND ONLY - EXPLICIT MATRIX
  #
  matrix:
  - MATVARIABLE11: matvar11
    MATVARIABLE: matvar1
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - MATVARIABLE12: matvar12
    MATVARIABLE: matvar2
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - MATVARIABLE21: matvar21
    MATVARIABLE: matvar1
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  - MATVARIABLE22: matvar21
    MATVARIABLE: matvar2
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

# "matrix.only" or "matrix.except" can be placed only under "for" node
for:
-
  matrix:
    only:
      - MATVARIABLE: matvar1
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        configuration: 'Release'

  environment:
    ENVVARIABLE: for1

  init:
    - "@echo off"
    - echo initializing
    - echo %skip_tags%
    - echo %platform%
    - echo %configuration%
    - echo %APPVEYOR_SAVE_CACHE_ON_ERROR%
    - echo %skip_tags%
    - echo %AUTHOR%
    - echo %APPVEYOR_BUILD_WORKER_IMAGE%
    - echo %MATVARIABLE22%
    - echo %MATVARIABLE%
    #
    - echo %ENVVARIABLE%

  install:
    - echo installing

  build_script:
    - echo building
    -
    - type MYARTIFACT.txt
    - type MYARTIFACT2.txt
    -
    - if not exist %MATVARIABLE%.txt echo %MATVARIABLE% > %MATVARIABLE%.txt

  after_build:
    - echo after_build
    - type MYARTIFACT.txt  > %APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%_1.txt
    - type MYARTIFACT2.txt > %APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%_2.txt

  artifacts:
    - path: "%APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%_1.txt"
      name: "myartifact"
    - path: "%APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%_2.txt"
      name: "myartifact2"

  # build cache to preserve files/folders between builds
  cache:
    - MyFile
    - '%MATVARIABLE%.txt'

  # provider names are case-sensitive!
  deploy:
    # Deploy to GitHub Releases
    - provider: GitHub
      artifact: FAKE_NO_ARTIFACT
      release: "%APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%"
      auth_token:
        secure: KzS1DumC2yBg2LGN9x3AemHFOjAdp+rD58rW5aGGpwW4Pfdwdm7AmRpYKprPY8Gs
      draft: false
      prerelease: false

  # I run my jobs manually
  # I do not want my email filling up
  notifications:
    - provider: Email
      on_build_success: false
      on_build_failure: false
      on_build_status_changed: false


-
  matrix:
    only:
      - MATVARIABLE: matvar2
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
        configuration: 'Release'

  environment:
    ENVVARIABLE: for2

  init:
    - "@echo off"
    - echo initializing
    - echo %skip_tags%
    - echo %platform%
    - echo %configuration%
    - echo %APPVEYOR_SAVE_CACHE_ON_ERROR%
    - echo %skip_tags%
    - echo %AUTHOR%
    - echo %APPVEYOR_BUILD_WORKER_IMAGE%
    - echo %ENVVARIABLE2%
    - echo %MATVARIABLE%
    #
    - echo %ENVVARIABLE%

  install:
    - echo installing

  build_script:
    - echo building
    -
    - type MYARTIFACT.txt
    - type MYARTIFACT2.txt
    -
    - if not exist %MATVARIABLE%.txt echo %MATVARIABLE% > %MATVARIABLE%.txt

  after_build:
    - echo after_build
    - type MYARTIFACT.txt  > %APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%_1.txt
    - type MYARTIFACT2.txt > %APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%_2.txt

  artifacts:
    - path: "%APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%_1.txt"
      name: "myartifact"
    - path: "%APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%_2.txt"
      name: "myartifact2"

  # build cache to preserve files/folders between builds
  cache:
    - MyFile
    - '%MATVARIABLE%.txt'

  # provider names are case-sensitive!
  deploy:
    # Deploy to GitHub Releases
    - provider: GitHub
      artifact: FAKE_NO_ARTIFACT
      release: "%APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%"
      auth_token:
        secure: KzS1DumC2yBg2LGN9x3AemHFOjAdp+rD58rW5aGGpwW4Pfdwdm7AmRpYKprPY8Gs
      draft: false
      prerelease: false

  # I run my jobs manually
  # I do not want my email filling up
  notifications:
    - provider: Email
      on_build_success: false
      on_build_failure: false
      on_build_status_changed: false

# "The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found"
# GitHub authorization is most probable reason for this. I believe your appveyor.yml cannot be read and not respected. Re-authorize (revoke and authorize again) GitHub at https://ci.appveyor.com/account,
# https://help.appveyor.com/discussions/problems/11287-the-build-phase-is-set-to-msbuild-mode-default-but-no-visual-studio-project-or-solution-files-were-found
# ALL OTHER CASES
-
  matrix:
    except:
      - MATVARIABLE: matvar1
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        configuration: 'Release'
      - MATVARIABLE: matvar2
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
        configuration: 'Release'
        
  init:
    - echo initializing
        
  install:
    - echo installing

  build_script:
    - echo building
