
version: 1.0.0-{build}-{branch}

# # Do not build on tags (GitHub, Bitbucket, GitLab, Gitea)
# skip_tags: true

# # Start builds on tags only (GitHub, BitBucket, GitLab, Gitea)
# skip_non_tags: true

# configuration for all branches starting from THE REGULAR EXPRESSION
# build in Release mode and deploy

branches:
  only:
    - master
    - development

for:
# configuration for "master" branch, build in Release mode
-
  branches:
    only:
      - master
  configuration: Release
# configuration for "development" branch, build in Debug mode
-
  branches:
    only:
      - development
  configuration: Debug
# "fall back" configuration for all other branches
# no "branches" section defined
configuration: Debug

# RHEAGROUP / CDP4-IME-Community-Edition
# https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/blob/338652b5a0f577732265d606d99c8ec56a56484c/appveyor.yml

# I can not get this to work (out of time)
# https://help.appveyor.com/discussions/problems/24462-using-appveyoryml-all-branches-do-not-build

image: Visual Studio 2019
environment:
  ENVVARIABLE1: envvar1
  matrix:
    - MATVARIABLE1: matvar1
      MATVARIABLE2: matvar2

init:
  - "@echo off"
  - echo initializing
  - if not defined APPVEYOR_REPO_TAG_NAME set APPVEYOR_REPO_TAG_NAME=NONE

install:
  - echo installing

build_script:
  - echo building
  - type MYARTIFACT.txt
  - type MYARTIFACT2.txt

after_build:
  - echo after_build
  - type MYARTIFACT.txt  > %APPVEYOR_PROJECT_NAME%_%APPVEYOR_REPO_TAG_NAME%_%APPVEYOR_BUILD_VERSION%_1.txt
  - type MYARTIFACT2.txt > %APPVEYOR_PROJECT_NAME%_%APPVEYOR_REPO_TAG_NAME%_%APPVEYOR_BUILD_VERSION%_2.txt

artifacts:
  - path: "%APPVEYOR_PROJECT_NAME%_%APPVEYOR_REPO_TAG_NAME%_%APPVEYOR_BUILD_VERSION%_1.txt"
    name: "myartifact"
  - path: "%APPVEYOR_PROJECT_NAME%_%APPVEYOR_REPO_TAG_NAME%_%APPVEYOR_BUILD_VERSION%_2.txt"
    name: "myartifact2"

deploy:
  release: "%APPVEYOR_PROJECT_NAME%_%APPVEYOR_REPO_TAG_NAME%"
  provider: GitHub
  auth_token:
    secure: KzS1DumC2yBg2LGN9x3AemHFOjAdp+rD58rW5aGGpwW4Pfdwdm7AmRpYKprPY8Gs
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
