
version: 0.1.0-{build}-{branch}

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
# skip_non_tags: true

branches:
  only:
    - master

image: Visual Studio 2019
environment:
  PGSOURCE: $(APPVEYOR_BUILD_FOLDER)\postgres
  PGBUILD: $(APPVEYOR_BUILD_FOLDER)\PGBUILD
  matrix:
    - MSYSTEM: MINGW64
      PG_GIT_BRANCH: REL_13_STABLE

install:
  - echo install
  - echo %PGSOURCE%
  # - git clone --depth 1 --single-branch --branch %PG_GIT_BRANCH% https://github.com/postgres/postgres.git %PGSOURCE%
  # - dir %PGSOURCE%

build_script:
  - sh -l -c "echo ${PGBUILD}"
  - :: BEGINNING WORK . . .
  - sh -l -c "alias shh=\"sh -l -c\""
  - sh -l -c "pwd"
  - sh -l -c "mkdir ${PGBUILD}"
  - sh -l -c "cd ${PGBUILD};   pwd"
  - sh -l -c "cd ${PGBUILD} && pwd
  - sh -l -c "export ALPHA=${PGBUILD}"
  - sh -l -c "echo ${ALPHA}"
  - sh -l -c "cd ${PGBUILD}"
  - sh -l -c "pwd"
  - sh -l -c "ls -alrt"
  - shh "ls -alrt"
  - cmd: >-
     echo BEGIN CHANGE TO DIR

     echo %PGBUILD%

     dir %PGBUILD%

     sh -l -c "

     pwd

     echo     %PGBUILD%

     echo     ${PGBUILD}

     ls -alrt ${PGBUILD}

     cd       ${PGBUILD}

     echo END CHANGE TO DIR "

after_build:
  - echo after_build