
# NOTE can not do gitflow branch names with hyphens in the branch names
version: 1.0.{build}.{branch}
# MAYBE DEV BRANCHES WOULD BE 1.1
#
# Do not build on tags (GitHub and BitBucket)
# NOT AN ENVIRONMENT VARIABLE (BUT DOES SKIP TAGS)
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
# skip_non_tags: true

# WILL DO BOTH COMBINATIONS
platform:
  - 'x64'
  - 'x86'

# WILL DO BOTH COMBINATIONS
configuration:
  - 'Debug'
  - 'Release'

environment:
  # these variables are common to all jobs
  AUTHOR: Andre Mikulec
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  # WILL DO BOTH COMBINATIONS
  matrix:
  - MATVARIABLE11: matvar11
    MATVARIABLE: matvar1
    APPVEYOR_BUILD_WORKER_IMAGE:  Visual Studio 2015
  - MATVARIABLE21: matvar21
    MATVARIABLE: matvar2
    APPVEYOR_BUILD_WORKER_IMAGE:  Visual Studio 2019

# # IS A LOGICAL 'OR'
# matrix:
#   exclude:
#     - platform: 'x86'
#     - configuration: 'Debug'

# https://devblogs.microsoft.com/setup/vswhere-now-searches-older-versions-of-visual-studio/
# https://www.nuget.org/packages/vswhere/
# Package Manager Install
# https://github.com/PoshCode/PSGit/blob/fc87f64f3e2b3926b6f15856977854c3ff04e8cb/appveyor.yml
# https://stackoverflow.com/questions/54305638/how-to-find-vswhere-exe-path

install:
  - curl -L -o vswhere.exe https://github.com/microsoft/vswhere/releases/download/2.8.4/vswhere.exe
  - vswhere -property catalog_productDisplayVersion

for:
-
  # "matrix.only" or "matrix.except" can be placed only under "for" node
  # IS A LOGICAL '??'
  matrix:
    except:
      - platform: 'x86'
      - configuration: 'Debug'

  environment:
    ENVVARIABLE1: envvar1

  init:
    - "@echo off"
    - echo initializing
    - echo %skip_tags%
    - echo %platform%
    - echo %configuration%
    - echo %APPVEYOR_SAVE_CACHE_ON_ERROR%
    - echo %skip_tags%
    - echo %AUTHOR%
    - echo %APPVEYOR_BUILD_WORKER_IMAGE%
    - echo %ENVVARIABLE1%
    - echo %MATVARIABLE%

  build_script:
    - echo building

-
  matrix:
    except:
      - platform: 'x86'
      - configuration: 'Debug'

  environment:
    ENVVARIABLE2: envvar2

  init:
    - "@echo off"
    - echo initializing
    - echo %skip_tags%
    - echo %platform%
    - echo %configuration%
    - echo %APPVEYOR_SAVE_CACHE_ON_ERROR%
    - echo %skip_tags%
    - echo %AUTHOR%
    - echo %APPVEYOR_BUILD_WORKER_IMAGE%
    - echo %ENVVARIABLE2%
    - echo %MATVARIABLE%

  build_script:
    - echo building
