
version: 1.0.0-{build}-{branch}

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
# skip_non_tags: true

branches:
  except:
    - /.*_devs?$/
    - /.*devtsts?$/
    - /.*devtests?$/
    - /.*sandbox(es)?$/
    - /.*playgrounds?$/

# RHEAGROUP / CDP4-IME-Community-Edition
# https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/blob/338652b5a0f577732265d606d99c8ec56a56484c/appveyor.yml

# I can not get this to work (out of time)
# https://help.appveyor.com/discussions/problems/24462-using-appveyoryml-all-branches-do-not-build

image: Visual Studio 2019
environment:
  ENVVARIABLE1: envvar1
  matrix:
    - MATVARIABLE1: matvar1
      MATVARIABLE2: matvar2

init:
  - "@echo off"
  - echo initializing
  - if not defined APPVEYOR_REPO_TAG_NAME set APPVEYOR_REPO_TAG_NAME=NOTTAGGED

install:
  - echo installing

build_script:
  - echo building
  - type MYARTIFACT.txt
  - type MYARTIFACT2.txt

after_build:
  - echo after_build
  - type MYARTIFACT.txt  > %APPVEYOR_PROJECT_NAME%_%APPVEYOR_REPO_TAG_NAME%_%APPVEYOR_BUILD_VERSION%_1.txt
  - type MYARTIFACT2.txt > %APPVEYOR_PROJECT_NAME%_%APPVEYOR_REPO_TAG_NAME%_%APPVEYOR_BUILD_VERSION%_2.txt

artifacts:
  - path: "%APPVEYOR_PROJECT_NAME%_%APPVEYOR_REPO_TAG_NAME%_%APPVEYOR_BUILD_VERSION%_1.txt"
    name: "myartifact"
  - path: "%APPVEYOR_PROJECT_NAME%_%APPVEYOR_REPO_TAG_NAME%_%APPVEYOR_BUILD_VERSION%_2.txt"
    name: "myartifact2"

# provider names are case-sensitive!
deploy:
  # FTP deployment provider settings
  - provider: FTP
    artifact: myartifact
    protocol: sftp
    host: frs.sourceforge.net
    username: andremikulec,andremikulec.u
    password:
      secure: 4gk4GyW4O5RooiOyGeRdoA==
    folder: /home/frs/project/andremikulec
    application:
    active_mode: false
    beta: true      # enable alternative FTP library for 'ftp' and 'ftps' modes
    debug: true     # show complete FTP log
  # Deploy to GitHub Releases
  - provider: GitHub
    artifact: myartifact
    release: "%APPVEYOR_PROJECT_NAME%_%APPVEYOR_REPO_TAG_NAME%"
    auth_token:
      secure: KzS1DumC2yBg2LGN9x3AemHFOjAdp+rD58rW5aGGpwW4Pfdwdm7AmRpYKprPY8Gs
    draft: false
    prerelease: false
