
version: 0.1.0-{build}-{branch}

# # Do not build on tags (GitHub and BitBucket)
# skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: true

# branches:
#   only:
#     - master

image: Visual Studio 2019
environment:
  ENVVARIABLE1: envvar1
  matrix:
    - MATVARIABLE1: matvar1
      MATVARIABLE2: matvar2

init:
  - "@echo off"
  - echo initializing
  - set

install:
  - echo installing
  - set

build_script:
  - echo buiding
  - set

after_build:
  - echo after build
  - echo MYARTIFACT  > myartifact.txt
  - echo MYARTIFACT2 > myartifact2.txt
  - set
  
artifacts:
  - path: "myartifact.txt"
    name: "myartifact"
  - path: "myartifact2.txt"
    name: "myartifact2"

deploy:
  release: "%APPVEYOR_PROJECT_SLUG%_%APPVEYOR_BUILD_VERSION%_Release"
  provider: GitHub
  auth_token:
    secure: KzS1DumC2yBg2LGN9x3AemHFOjAdp+rD58rW5aGGpwW4Pfdwdm7AmRpYKprPY8Gs
  # artifact: "myartifact"
  draft: false
  prerelease: false
  on:
    branch: master
