
# NOTE can not do gitflow branch names with hyphens in the branch names
version: 1.0.{build}.{branch}
# MAYBE DEV BRANCHES WOULD BE 1.1
#
# Do not build on tags (GitHub and BitBucket)
# NOT AN ENVIRONMENT VARIABLE (BUT DOES SKIP TAGS)
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
# skip_non_tags: true

platform:
  - 'x64'
  - 'x86'

configuration:
  - 'Debug'
  - 'Release'

environment:
  # these variables are common to all jobs
  AUTHOR: Andre Mikulec
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
  - MATVARIABLE11: matvar11
    MATVARIABLE: matvar1
    image: Visual Studio 2015
  - MATVARIABLE21: matvar21
    MATVARIABLE: matvar2
    image: Visual Studio 2019

# # IS A LOGICAL 'OR'
# matrix:
#   exclude:
#     - platform: 'x86'
#     - configuration: 'Debug'

# IS A LOGICAL '??'
matrix:
  except:
    - platform: 'x86'
    - configuration: 'Debug'

for:
-
  environment:
    ENVVARIABLE1: envvar1

  init:
    - "@echo off"
    - echo initializing
    - echo %skip_tags%
    - echo %platform%
    - echo %configuration%
    - echo %APPVEYOR_SAVE_CACHE_ON_ERROR%
    - echo %skip_tags%
    - echo %AUTHOR%
    - echo %image%
    - echo %ENVVARIABLE1%
    - echo %MATVARIABLE%

  install:
    - echo installing

  build_script:
    - echo building
    - type MYARTIFACT.txt
    - type MYARTIFACT2.txt
    - if not exist %MATVARIABLE%.txt echo %MATVARIABLE% > %MATVARIABLE%.txt

  after_build:
    - echo after_build
    - type MYARTIFACT.txt  > %APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%_1.txt
    - type MYARTIFACT2.txt > %APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%_2.txt

  artifacts:
    - path: "%APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%_1.txt"
      name: "myartifact"
    - path: "%APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%_2.txt"
      name: "myartifact2"

  # build cache to preserve files/folders between builds
  cache:
    - '%MATVARIABLE%.txt'

  # provider names are case-sensitive!
  deploy:
    # Deploy to GitHub Releases
    - provider: GitHub
      artifact: myartifact, myartifact2
      release: "%APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%"
      auth_token:
        secure: KzS1DumC2yBg2LGN9x3AemHFOjAdp+rD58rW5aGGpwW4Pfdwdm7AmRpYKprPY8Gs
      draft: false
      prerelease: false

  # I run my jobs manually
  # I do not want my email filling up
  notifications:
    - provider: Email
      on_build_success: false
      on_build_failure: false
      on_build_status_changed: false

-
  environment:
    ENVVARIABLE2: envvar2

  init:
    - "@echo off"
    - echo initializing
    - echo %skip_tags%
    - echo %platform%
    - echo %configuration%
    - echo %APPVEYOR_SAVE_CACHE_ON_ERROR%
    - echo %skip_tags%
    - echo %AUTHOR%
    - echo %image%
    - echo %ENVVARIABLE2%
    - echo %MATVARIABLE%

  install:
    - echo installing

  build_script:
    - echo building
    - type MYARTIFACT.txt
    - type MYARTIFACT2.txt
    - if not exist %MATVARIABLE%.txt echo %MATVARIABLE% > %MATVARIABLE%.txt

  after_build:
    - echo after_build
    - type MYARTIFACT.txt  > %APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%_1.txt
    - type MYARTIFACT2.txt > %APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%_2.txt

  artifacts:
    - path: "%APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%_1.txt"
      name: "myartifact"
    - path: "%APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%_2.txt"
      name: "myartifact2"

  # build cache to preserve files/folders between builds
  cache:
    - '%MATVARIABLE%.txt'

  # provider names are case-sensitive!
  deploy:
    # Deploy to GitHub Releases
    - provider: GitHub
      artifact: myartifact, myartifact2
      release: "%APPVEYOR_PROJECT_NAME%_%APPVEYOR_BUILD_VERSION%"
      auth_token:
        secure: KzS1DumC2yBg2LGN9x3AemHFOjAdp+rD58rW5aGGpwW4Pfdwdm7AmRpYKprPY8Gs
      draft: false
      prerelease: false

  # I run my jobs manually
  # I do not want my email filling up
  notifications:
    - provider: Email
      on_build_success: false
      on_build_failure: false
      on_build_status_changed: false
