
# NOTE can not do gitflow branch names with hyphens in the branch names

# WEIRD -SOMETIMES - TWO TAGS IN THE SAME BRANCH
version: 1.0.{build}.{branch}
# MAYBE DEV BRANCHES WOULD BE 1.1
#

#
# KEEP HERE
#

# Do not build on tags (GitHub and BitBucket)
# NOT AN ENVIRONMENT VARIABLE (BUT DOES SKIP TAGS)
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
# skip_non_tags: true

# ( ) IS A LOGICAL 'AND'
# (-) IS A LOGICAL 'OR'

# IMPLIED - ROOT MATRIX

# WILL DO BOTH COMBINATIONS
platform:
  - 'x64'
  - 'x86'

# WILL DO BOTH COMBINATIONS
configuration:
  - 'Debug'
  - 'Release'

# WORKS (RESTRICTS ROOT LEVEL)
matrix:
  exclude:
    # ( ) IS A LOGICAL 'AND'
    # (-) IS A LOGICAL 'OR'
    - platform: 'x86'
      configuration: 'Debug'

init:
 - sh: if [ "${CONFIGURATION}" = "Debug" ] && ; then exit 0; else  ;fi
 - sh: if [ "${PLATFORM}" = "x86" ]; then exit 0; fi 

environment:
  #
  # these variables are common to all jobs
  #
  AUTHOR: Andre Mikulec
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  #
  # THE ONE AND ONLY - EXPLICIT MATRIX
  #
  matrix:
  - MATVARIABLE11: matvar11
    MATVARIABLE: matvar1
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - MATVARIABLE12: matvar12
    MATVARIABLE: matvar2
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - MATVARIABLE21: matvar21
    MATVARIABLE: matvar1
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  - MATVARIABLE22: matvar21
    MATVARIABLE: matvar2
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

# "matrix.only" or "matrix.except" can be placed only under "for" node
for:
-
  matrix:
    only:
      - MATVARIABLE: matvar1
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        configuration: 'Release'

  environment:
    ENVVARIABLE: for1

  init:
    - "@echo off"
    - echo initializing
    - echo %skip_tags%
    - echo %platform%
    - echo %configuration%
    - echo %APPVEYOR_SAVE_CACHE_ON_ERROR%
    - echo %skip_tags%
    - echo %AUTHOR%
    - echo %APPVEYOR_BUILD_WORKER_IMAGE%
    - echo %MATVARIABLE22%
    - echo %MATVARIABLE%
    #
    - echo %ENVVARIABLE%
    
  install:
    - echo installing  
    
  build_script:
    - echo building

-
  matrix:
    only:
      - MATVARIABLE: matvar2
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
        configuration: 'Release'

  environment:
    ENVVARIABLE: for2

  init:
    - "@echo off"
    - echo initializing
    - echo %skip_tags%
    - echo %platform%
    - echo %configuration%
    - echo %APPVEYOR_SAVE_CACHE_ON_ERROR%
    - echo %skip_tags%
    - echo %AUTHOR%
    - echo %APPVEYOR_BUILD_WORKER_IMAGE%
    - echo %ENVVARIABLE2%
    - echo %MATVARIABLE%
    #
    - echo %ENVVARIABLE%

  install:
    - echo installing  

  build_script:
    - echo building
