
version: 1.0.0-{build}-{branch}

# # Do not build on tags (GitHub, Bitbucket, GitLab, Gitea)
# skip_tags: true

# Start builds on tags only (GitHub, BitBucket, GitLab, Gitea)
skip_non_tags: true

# branches:
#   only:
#     - master

image: Visual Studio 2019
environment:
  ENVVARIABLE1: envvar1
  matrix:
    - MATVARIABLE1: matvar1
      MATVARIABLE2: matvar2

init:
  - "@echo off"
  - echo initializing
  - set

install:
  - echo installing

build_script:
  - echo building
  - type MYARTIFACT.txt
  - type MYARTIFACT2.txt

after_build:
  - echo after_build
  - type MYARTIFACT.txt  > %APPVEYOR_PROJECT_NAME%_%APPVEYOR_REPO_TAG_NAME%_%APPVEYOR_BUILD_VERSION%_1.txt
  - type MYARTIFACT2.txt > %APPVEYOR_PROJECT_NAME%_%APPVEYOR_REPO_TAG_NAME%_%APPVEYOR_BUILD_VERSION%_2.txt
  
artifacts:
  - path: "AppVeyor_Tests_%APPVEYOR_REPO_TAG_NAME%_%APPVEYOR_BUILD_VERSION%_1.txt"
    name: "myartifact"
  - path: "AppVeyor_Tests_%APPVEYOR_REPO_TAG_NAME%_%APPVEYOR_BUILD_VERSION%_2.txt"
    name: "myartifact2"

deploy:
  release: "AppVeyor_Tests_%APPVEYOR_REPO_TAG_NAME%"
  provider: GitHub
  auth_token:
    secure: KzS1DumC2yBg2LGN9x3AemHFOjAdp+rD58rW5aGGpwW4Pfdwdm7AmRpYKprPY8Gs
  draft: false
  prerelease: false



