
version: 0.1.0-{build}-{branch}

# # Do not build on tags (GitHub, Bitbucket, GitLab, Gitea)
# skip_tags: true

# Start builds on tags only (GitHub, BitBucket, GitLab, Gitea)
skip_non_tags: true

# branches:
#   only:
#     - master

image: Visual Studio 2019
environment:
  ENVVARIABLE1: envvar1
  matrix:
    - MATVARIABLE1: matvar1
      MATVARIABLE2: matvar2

init:
  - "@echo off"
  - echo initializing
  - set

install:
  - echo installing

build_script:
  - echo building

after_build:
  - echo after build
  - echo MYARTIFACT  > %APPVEYOR_PROJECT_SLUG%_myartifact_%APPVEYOR_BUILD_VERSION%.txt
  - echo MYARTIFACT2 > %APPVEYOR_PROJECT_SLUG%_myartifact2_%APPVEYOR_BUILD_VERSION%.txt
